version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "src/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/Picocrypt/dialog"
      - dependency-name: "github.com/Picocrypt/giu"
      - dependency-name: "github.com/Picocrypt/imgui-go"
      - dependency-name: "github.com/Picocrypt/infectious"
      - dependency-name: "github.com/Picocrypt/serpent"
      - dependency-name: "github.com/Picocrypt/zxcvbn-go"
      - dependency-name: "github.com/Picocrypt/gl"
      - dependency-name: "github.com/Picocrypt/glfw"
      - dependency-name: "github.com/Picocrypt/mainthread"
      - dependency-name: "github.com/Picocrypt/w32"
