name: AI Review (OpenRouter - minimal)

on:
  pull_request:
    branches: [main]          # review PRs into main
    types:    [opened, synchronize]

permissions:
  contents:       read
  pull-requests:  write        # so the bot can add comments

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - uses: AidentErfurt/bc-ai-reviewer@main
        with:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

          AI_PROVIDER:   openrouter
          AI_MODEL:      microsoft/mai-ds-r1:free
          AI_API_KEY:    ${{ secrets.OPENROUTER_API_KEY }}
