name: "AI inference"
on:
  pull_request:
    types: [opened, reopened, synchronize]

# Minimal permissions required by the action + permissions for the AI to act on PRs/issues if you want that.
permissions:
  contents: read
  models: read
  pull-requests: read
  issues: write
  checks: write
  statuses: write

jobs:
  inference:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional, safe default)
        uses: actions/checkout@v5.0.0

      - name: AI Inference with GitHub Tools
        id: inference
        uses: actions/ai-inference@v2.0.1
        with:
          prompt: "List my open pull requests and create a summary"
          enable-github-mcp: true
          # token used for calling the Models endpoint - use the builtin GITHUB_TOKEN
          token: ${{ github.token }}
          # github-mcp-token MUST be a Personal Access Token (PAT) stored in a repository secret.
          # Create a PAT and save it in Settings → Secrets → Actions as e.g. USER_PAT
          github-mcp-token: ${{ secrets.GH2_TOKEN }}

      - name: Print output
        run: |
          echo "AI response:"
          echo "${{ steps.inference.outputs.response }}"
