name: 'AI inference'
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  models: read    
    
jobs:
  inference:
    runs-on: ubuntu-latest
    steps:
    - name: AI Inference with GitHub Tools
      id: inference
      uses: actions/ai-inference@v2.0.1
      with:
        prompt: 'List my open pull requests and create a summary'
        enable-github-mcp: true
        token: ${{ secrets.GH2_TOKEN }}
