name: pr-test-build-linux

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main

jobs:
  pr-test-build-linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '>=1.24'
        check-latest: true
        cache: false

    - name: Update repository
      run: |
        sudo apt update

    - name: Install packages
      run: |
        sudo apt install -y gcc xorg-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa wget

    - name: Install dependencies
      run: |
        cd src
        go mod download

    - name: Build
      run: |
        cd src
        go build -v -ldflags="-s -w" -o Picocrypt-NG Picocrypt-NG.go
      env:
        CGO_ENABLED: 1
        GOAMD64: v1

    - name: Compress with upx
      run: |
        wget -O upx.tar.xz https://github.com/upx/upx/releases/download/v5.0.2/upx-5.0.2-amd64_linux.tar.xz
        tar -xf upx.tar.xz
        upx-5.0.2-amd64_linux/upx --lzma src/Picocrypt-NG

    - name: Package as .deb
      run: |
        wget https://github.com/user-attachments/files/21703014/Picocrypt-NG.zip
        python -m zipfile -e Picocrypt-NG.zip Picocrypt-NG
        cp src/Picocrypt-NG Picocrypt-NG/Picocrypt-NG/usr/bin/picocrypt-ng-gui
        VERSION=$(cat VERSION)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version: $VERSION" >> Picocrypt-NG/Picocrypt-NG/DEBIAN/control
        echo "Version=$VERSION" >> Picocrypt-NG/Picocrypt-NG/usr/share/applications/picocrypt-ng.desktop
        cd Picocrypt-NG
        dpkg-deb -Zxz --build --root-owner-group Picocrypt-NG

    - name: Prepare to upload artifacts
      run: |
        mkdir out
        mv src/Picocrypt-NG out
        mv Picocrypt-NG/Picocrypt-NG.deb out
        rm -rf src
        rm -rf Picocrypt-NG
        mv out/Picocrypt-NG .
        mv out/Picocrypt-NG.deb .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: |
          Picocrypt-NG
          Picocrypt-NG.deb
        if-no-files-found: error
        compression-level: 9
